/* GENERATED from contract.json -- do not edit */
#ifndef CONTRACT_GEN_H
#define CONTRACT_GEN_H
#define CONTRACT_MODEL_NAME "mlp16k"
#define CONTRACT_TARGET_TRIPLE "x86_64-unknown-linux-gnu"
#define CONTRACT_BOUND_METHOD "static_from_stream_layout"
#define CONTRACT_BOUND_KNOWN 1
#define CONTRACT_BOUNDED_BYTES 786476L
#define CONTRACT_PER_CALL_BYTES 65580L
#define CONTRACT_CONST_BYTES 720896L
#define CONTRACT_KERNEL_STACK_BYTES_KNOWN 1
#define CONTRACT_KERNEL_STACK_BYTES 16L
#define CONTRACT_ARTIFACT_BYTES 733979L
#define CONTRACT_ARTIFACT_SHA256 "4d6f3807d37f0902cc6e4d985e69f68de3f93973bbcc3f1ef03d6a4c084f344f"
#define CONTRACT_ENTRY "module.infer"
#define CONTRACT_INPUT_RANK 2
#define CONTRACT_INPUT_SHAPE {1, 9}
#define CONTRACT_INPUT_ELEMS 9
#define CONTRACT_OUTPUT_RANK 2
#define CONTRACT_OUTPUT_SHAPE {1, 2}
#define CONTRACT_OUTPUT_ELEMS 2
#define CONTRACT_SHAPES_STATIC 1
#define CONTRACT_NUM_INPUTS 1
#define CONTRACT_NUM_OUTPUTS 1
#define CONTRACT_DTYPES_ALL_F32 1
#define CONTRACT_DRIVER "local-sync"
#endif
