#!/usr/bin/env python3
"""E24c / F4: generate an MLIR model with MANY module-resident constants.

Why this model exists
---------------------
E24b/D38 removed a 24-segment positional truncation from
`make_contract.py::subset_sum_match`. The truncation made the tool write a FALSE
statement into an otherwise honest contract ("module constant total ... NOT
matched by artifact .rodata segments") whenever a model produced more than 24
constant segments. That claim was pinned only by a SYNTHESISED 31-integer array
in `harness/contract_negative_tests.py`; the external review of v0.20 (F4)
pointed out that the repository preserved no real IREE artifact exhibiting it,
so the claim was not reproducible from repository contents.

This generator closes that gap. Compiled with the stock flag
`--iree-stream-resource-max-allocation-size=1024`, it yields 33 data segments
(32 embedded constant slabs of 1024 B plus one external segment), i.e. more than
the old 24 cap, on a completely ordinary single invocation.

Two shapes matter and both are deliberate:
  * N separate 16x16 f32 constants chained through `linalg.matmul` so constant
    folding cannot collapse them into one;
  * a final 16x32 tail so the module has TWO dispatches. With a single dispatch
    iree-compile names the linked executable `module_infer_dispatch_0_*` and the
    dump directory then contains no file carrying the .mlir basename, which
    `make_contract.py`'s one-invocation check (D10) correctly refuses. The tail
    forces the `module_<basename>_linked_*` name the check looks for.

Usage: python3 harness/gen_model_manyconst.py [--n 31] [--seed 7] --out model.mlir
"""
import argparse
import random


def build(n, seed):
    rng = random.Random(seed)

    def dense2(rows, cols):
        return "[" + ", ".join(
            "[" + ", ".join("%.4f" % rng.uniform(-0.5, 0.5) for _ in range(cols)) + "]"
            for _ in range(rows)) + "]"

    L = [
        "// GENERATED by harness/gen_model_manyconst.py (E24c/F4) -- do not hand-edit.",
        "// %d module-resident 16x16 f32 constants chained so none folds away, plus a" % n,
        "// 16x32 tail that forces a second dispatch (see the module docstring)." ,
        "func.func @infer(%arg0: tensor<1x16xf32>) -> tensor<1x32xf32> {",
        "  %zero = arith.constant 0.0 : f32",
    ]
    cur = "%arg0"
    for i in range(n):
        L.append("  %w{0} = arith.constant dense<{1}> : tensor<16x16xf32>".format(i, dense2(16, 16)))
        L.append("  %init{0} = tensor.empty() : tensor<1x16xf32>".format(i))
        L.append("  %f{0} = linalg.fill ins(%zero : f32) outs(%init{0} : tensor<1x16xf32>) "
                 "-> tensor<1x16xf32>".format(i))
        L.append("  %m{0} = linalg.matmul ins({1}, %w{0} : tensor<1x16xf32>, tensor<16x16xf32>) "
                 "outs(%f{0} : tensor<1x16xf32>) -> tensor<1x16xf32>".format(i, cur))
        cur = "%m{0}".format(i)
    L.append("  %wt = arith.constant dense<{0}> : tensor<16x32xf32>".format(dense2(16, 32)))
    L.append("  %initt = tensor.empty() : tensor<1x32xf32>")
    L.append("  %ft = linalg.fill ins(%zero : f32) outs(%initt : tensor<1x32xf32>) -> tensor<1x32xf32>")
    L.append("  %out = linalg.matmul ins({0}, %wt : tensor<1x16xf32>, tensor<16x32xf32>) "
             "outs(%ft : tensor<1x32xf32>) -> tensor<1x32xf32>".format(cur))
    L.append("  return %out : tensor<1x32xf32>")
    L.append("}")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--n", type=int, default=31, help="number of 16x16 constants (default 31)")
    ap.add_argument("--seed", type=int, default=7, help="RNG seed -- fixed so the .mlir is deterministic")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    with open(a.out, "w") as f:
        f.write(build(a.n, a.seed))
    print("wrote %s (n=%d, seed=%d)" % (a.out, a.n, a.seed))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
