#!/usr/bin/env python3
"""E26c / C-1: generate an MLIR model with MORE THAN ONE result.

Why this model exists
---------------------
Both allocation extractors (`harness/static_mem_bound.py::parse_alloc_ir` and
`harness/mlir_alloc_walk.py::parse_alloc_ir_structural`) refuse a bound when the
entry body contains a `stream.*` op they cannot size (D13's fail-closed policy).
`stream.resource.subview` was missing from both whitelists, and IREE emits it for
every model whose results it packs into a single output slab -- i.e. essentially
every multi-output model. The result was a type (B) defect, an OVER-REJECTION:
an ordinary model compiled by a stock single `iree-compile` invocation came out
`UNKNOWN_BOUND` even though the parser had already sized the one real allocation
soundly, and conservatively at that.

The layout IR of this model is the evidence. One allocation, two views of it:

    %result, %result_timepoint = stream.resource.alloca ... {%c128}
    %1 = stream.resource.subview %result[%c0]  ... {%c128} -> ... {%c32}
    %2 = stream.resource.subview %result[%c64] ... {%c128} -> ... {%c16}

32 + 16 = 48 bytes of results live inside a 128-byte slab (each output is padded
to the 64-byte HAL alignment). The subviews allocate nothing; the alloca already
covers them, which is why counting the alloca alone is sound.

Repository rule (D43): a fix justified by "a real model does X" needs that model
in the tree, generated by committed code, or the justification is not
reproducible from repository contents. This generator is that model.

Two shapes are deliberate:
  * NON-SPLAT random weights, so the module really carries module-resident
    constants. A `dense<0.05>` splat is materialized without a constant slab and
    would have made `module_resident_constant_bytes` 0, testing less.
  * two results of DIFFERENT sizes (1x8 and 1x4), so the two subviews carry
    different offsets and different window sizes. A pair of equal windows could
    satisfy the containment check by coincidence.

Usage: python3 harness/gen_model_multiout.py [--seed 11] --out model.mlir
"""
import argparse
import random


def build(seed):
    rng = random.Random(seed)

    def dense2(rows, cols):
        return "[" + ", ".join(
            "[" + ", ".join("%.4f" % rng.uniform(-0.5, 0.5) for _ in range(cols)) + "]"
            for _ in range(rows)) + "]"

    return "\n".join([
        "// GENERATED by harness/gen_model_multiout.py (E26c/C-1) -- do not hand-edit.",
        "// Two results of different sizes, so iree-compile packs them into ONE",
        "// stream.resource.alloca and emits two stream.resource.subview windows.",
        "func.func @infer(%arg0: tensor<1x16xf32>) -> (tensor<1x8xf32>, tensor<1x4xf32>) {",
        "  %zero = arith.constant 0.0 : f32",
        "  %w0 = arith.constant dense<" + dense2(16, 8) + "> : tensor<16x8xf32>",
        "  %w1 = arith.constant dense<" + dense2(8, 4) + "> : tensor<8x4xf32>",
        "  %i0 = tensor.empty() : tensor<1x8xf32>",
        "  %f0 = linalg.fill ins(%zero : f32) outs(%i0 : tensor<1x8xf32>) -> tensor<1x8xf32>",
        "  %m0 = linalg.matmul ins(%arg0, %w0 : tensor<1x16xf32>, tensor<16x8xf32>) "
        "outs(%f0 : tensor<1x8xf32>) -> tensor<1x8xf32>",
        "  %i1 = tensor.empty() : tensor<1x4xf32>",
        "  %f1 = linalg.fill ins(%zero : f32) outs(%i1 : tensor<1x4xf32>) -> tensor<1x4xf32>",
        "  %m1 = linalg.matmul ins(%m0, %w1 : tensor<1x8xf32>, tensor<8x4xf32>) "
        "outs(%f1 : tensor<1x4xf32>) -> tensor<1x4xf32>",
        "  return %m0, %m1 : tensor<1x8xf32>, tensor<1x4xf32>",
        "}",
        "",
    ])


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=11)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    open(a.out, "w").write(build(a.seed))
    print("wrote", a.out)
