#!/usr/bin/env python3
"""E25: generate ONE canonical model that every execution path shares.

Why this exists
---------------
Before E25 the two paths ran DIFFERENT models and only the interface matched:

  OnAIR fixture : mlp_9x65536x2, hidden 65536, weights in an external weights.npz
                  (2,884,078 B), model.vmfb 10,642 B (no weights inside)
  cFS deployment: mlp16k,        hidden 16384, weights BAKED into the MLIR,
                  model.vmfb 733,979 B

So "the same OnAIR AI model was deployed to cFS" had no basis (docs/EVIDENCE_v0.18_E23.md
section 2; the numbers are in docs/plans/E25_same_model_equivalence.md section 1).

This generator emits, from ONE seeded weight draw:

  <out>/model_canonical.mlir   baked-weight MLIR  -> compiled ONCE, shared by
                               OnAIR-IREE, native C and the cFS app
  <out>/weights.npz            the SAME w0/w1     -> used only by the NumPy
                               reference (plugins/python_learner)
  <out>/inputs.npy             the fixed input set the comparison runs on
  <out>/manifest.json          sha256 of all three + the parameters

Because the deployed artifact is the baked vmfb, weights.npz never enters a
deployment path -- which is what the external review asked for when it noted that
weights.npz sits outside the contract.

The MLIR body is the same 2-layer form characterize_baked.py::make_src has used
since E6b (x @ w0 @ w1, no activation), so the NumPy reference is exactly
`x @ w0 @ w1` with no modelling ambiguity.

Input distribution: drawn to resemble the OnAIR CSV telemetry the plugins actually
receive (onair/data/raw_telemetry_data/.../Errors/*.csv), whose first field is a
~9.5e8 epoch timestamp and whose remaining fields are O(1)-O(1e3). That spread is
deliberate -- it is the regime where absolute and relative error disagree, which is
why the pass criteria accept either (plan section 3.2).

Usage: python3 harness/gen_model_canonical.py --outdir results/e25_equivalence/model
"""
import argparse
import hashlib
import json
import os

import numpy as np

# OnAIR CSV telemetry columns the plugins see, with the observed scale of each.
# (Time is delivered as a float epoch, e.g. 946689839.0.)
TELEMETRY_COLUMNS = [
    ("TIME", 9.466898e8, 5.0e2),
    ("VOLTAGE", 15.0, 3.0),
    ("CURRENT", 4.0, 1.0),
    ("THRUST", -100.0, 100.0),
    ("ALTITUDE", 2000.0, 50.0),
    ("ACCELERATION", -0.25, 0.25),
    ("TEMPERATURE", 34.29, 0.5),
    ("SCIENCE_COLLECTION", 0.0, 0.5),
    ("ERROR_STATE", 0.0, 0.5),
]


def make_baked_mlir(n_in, n_h, n_out, w0, w1):
    """Same shape as characterize_baked.py::make_src (E6b onward)."""
    def d(a):
        return "dense<[" + ",".join("%.6e" % v for v in a.reshape(-1)) + "]>"
    return f"""// GENERATED by harness/gen_model_canonical.py (E25) -- do not hand-edit.
// Baked-weight 2-layer MLP: infer(x) = x @ w0 @ w1  (no activation).
// The identical w0/w1 are written to weights.npz for the NumPy reference.
func.func @infer(%x: tensor<1x{n_in}xf32>) -> tensor<1x{n_out}xf32> {{
  %s0 = arith.constant dense<[{n_in}, {n_h}]> : tensor<2xi64>
  %s1 = arith.constant dense<[{n_h}, {n_out}]> : tensor<2xi64>
  %w0 = arith.constant {d(w0)} : tensor<{n_in * n_h}xf32>
  %w0r = tensor.reshape %w0(%s0) : (tensor<{n_in * n_h}xf32>, tensor<2xi64>) -> tensor<{n_in}x{n_h}xf32>
  %w1 = arith.constant {d(w1)} : tensor<{n_h * n_out}xf32>
  %w1r = tensor.reshape %w1(%s1) : (tensor<{n_h * n_out}xf32>, tensor<2xi64>) -> tensor<{n_h}x{n_out}xf32>
  %z0 = arith.constant dense<0.0> : tensor<1x{n_h}xf32>
  %h = linalg.matmul ins(%x, %w0r : tensor<1x{n_in}xf32>, tensor<{n_in}x{n_h}xf32>) outs(%z0 : tensor<1x{n_h}xf32>) -> tensor<1x{n_h}xf32>
  %z1 = arith.constant dense<0.0> : tensor<1x{n_out}xf32>
  %o = linalg.matmul ins(%h, %w1r : tensor<1x{n_h}xf32>, tensor<{n_h}x{n_out}xf32>) outs(%z1 : tensor<1x{n_out}xf32>) -> tensor<1x{n_out}xf32>
  return %o : tensor<1x{n_out}xf32>
}}
"""


def sha256_file(path):
    return hashlib.sha256(open(path, "rb").read()).hexdigest()


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--n-in", type=int, default=9)
    ap.add_argument("--n-hidden", type=int, default=16384,
                    help="default matches E14's mlp16k so the contract is comparable")
    ap.add_argument("--n-out", type=int, default=2)
    ap.add_argument("--n-inputs", type=int, default=64, help="fixed comparison input set size")
    ap.add_argument("--seed", type=int, default=20260909)
    ap.add_argument("--outdir", required=True)
    a = ap.parse_args()
    os.makedirs(a.outdir, exist_ok=True)

    rng = np.random.default_rng(a.seed)
    w0 = (rng.standard_normal((a.n_in, a.n_hidden)) * 0.1).astype(np.float32)
    w1 = (rng.standard_normal((a.n_hidden, a.n_out)) * 0.1).astype(np.float32)

    cols = TELEMETRY_COLUMNS[:a.n_in]
    if len(cols) < a.n_in:                       # more inputs than named columns
        cols = cols + [("EXTRA_%d" % i, 0.0, 1.0) for i in range(a.n_in - len(cols))]

    # TWO input regimes, both needed. Measured while building this: neither plugin
    # normalises -- plugins/{compiled_learner,python_learner} both do a bare
    # float(v) on the raw CSV field -- so the real pipeline feeds a ~9.5e8 epoch
    # straight into the model. That IS the deployed behaviour and must be tested.
    # But it also means one column outweighs the rest by 5-9 orders of magnitude,
    # so a comparison on that regime alone effectively exercises a single column
    # (observed: max abs err 4.1e3 against a ~1.3e9 output, i.e. rel 3.2e-6).
    # The "normalized" regime keeps every column O(1) so the equivalence check
    # actually covers the whole input space. The pass criteria are unchanged --
    # only the input set is widened, and the reason is recorded here and in the
    # manifest rather than discovered after the fact.
    n_each = a.n_inputs // 2
    x_telemetry = np.stack([rng.normal(mu, sd, size=n_each) for _n, mu, sd in cols],
                           axis=1).astype(np.float32)
    x_normalized = rng.normal(0.0, 1.0, size=(a.n_inputs - n_each, a.n_in)).astype(np.float32)
    x = np.concatenate([x_telemetry, x_normalized], axis=0)
    regimes = ["telemetry"] * n_each + ["normalized"] * (a.n_inputs - n_each)

    mlir_path = os.path.join(a.outdir, "model_canonical.mlir")
    npz_path = os.path.join(a.outdir, "weights.npz")
    npy_path = os.path.join(a.outdir, "inputs.npy")
    with open(mlir_path, "w") as f:
        f.write(make_baked_mlir(a.n_in, a.n_hidden, a.n_out, w0, w1))
    np.savez(npz_path, w0=w0, w1=w1)
    np.save(npy_path, x)

    manifest = {
        "experiment": "E25",
        "purpose": "one canonical model shared by every execution path; weights.npz is the "
                   "NumPy reference's copy of the SAME weights that are baked into the MLIR",
        "generator": "harness/gen_model_canonical.py",
        "params": {"n_in": a.n_in, "n_hidden": a.n_hidden, "n_out": a.n_out,
                   "n_inputs": a.n_inputs, "seed": a.seed},
        "input_columns": [c[0] for c in cols],
        "input_regimes": regimes,
        "input_regime_note": "telemetry = the raw OnAIR CSV scale the plugins actually feed "
                             "(no normalisation anywhere in either plugin; verified by reading "
                             "their update() methods); normalized = every column O(1), so the "
                             "equivalence check is not dominated by the epoch column",
        "sha256": {os.path.basename(p): sha256_file(p) for p in (mlir_path, npz_path, npy_path)},
        "reference_expression": "y = x @ w0 @ w1  (float32, no activation)",
    }
    mpath = os.path.join(a.outdir, "manifest.json")
    with open(mpath, "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    print("wrote %s (%.1f MB), weights.npz, inputs.npy, manifest.json"
          % (mlir_path, os.path.getsize(mlir_path) / 1e6))
    for k, v in manifest["sha256"].items():
        print("  %-22s %s" % (k, v[:16]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
