#!/usr/bin/env bash
# Build the native learner against the minimal IREE runtime (local-sync, embedded ELF, no threading).
#
# Usage: bash build.sh [CONTRACT_JSON] [MODEL_NAME]
#   CONTRACT_JSON  contract of the SAME iree-compile invocation that produced the vmfb this
#                  binary will run (EVIDENCE_v0.7 §1.3). Default: ../contracts/contract.filled.example.json
#   MODEL_NAME     optional; names the output binary native_learner_<MODEL_NAME> so one
#                  binary per model/contract can coexist (default output: native_learner)
# Environment (defaults reproduce the historical x86-64 build exactly):
#   IREE_SRC     IREE source tree (default /tmp/iree-src); IREE_BUILD runtime build dir (default $IREE_SRC/build-rt)
#   CC           compiler (default gcc; e.g. aarch64-linux-gnu-gcc with IREE_BUILD=.../build-rt-aarch64)
#   EXTRA_CFLAGS / EXTRA_LDFLAGS  appended verbatim (e.g. EXTRA_LDFLAGS=-static for a guest binary)
# The contract header is ALWAYS regenerated by harness/gen_contract_header.py; never hand-edit contract_gen.h.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IREE_SRC="${IREE_SRC:-/tmp/iree-src}"; B="${IREE_BUILD:-$IREE_SRC/build-rt}"; CC="${CC:-gcc}"
CONTRACT="${1:-$HERE/../contracts/contract.filled.example.json}"; MODEL_NAME="${2:-}"
if [ "${CONTRACT#/}" = "$CONTRACT" ]; then CONTRACT="$PWD/$CONTRACT"; fi   # relative to the caller's cwd
cd "$HERE"
OUT="native_learner${MODEL_NAME:+_$MODEL_NAME}"
# --allow-unknown-stack (E24b): the DEFAULT contract here is
# contracts/contract.filled.example.json, an example fixture with no ELF stack
# analysis, so D13/D15's "refuse a bound-known header with an implicit 0 B kernel
# stack" gate refuses it. That has been true since E15 and made the smoke test
# CLAUDE.md documents (`cd native && bash build.sh`) fail with rc=1 -- verified
# against the pre-E24b generator, so it is not caused by any gate added here.
# A real deployment passes its own contract (argument 1) built by make_contract.py
# WITH --elf-analysis, and that path does not need this flag; keeping it here only
# preserves the documented smoke test on the example fixture.
python3 ../harness/gen_contract_header.py "$CONTRACT" contract_gen.h --allow-unknown-stack >/dev/null
LIBS="$(find "$B/runtime" -name "*.a" | tr "\n" " ") $B/build_tools/third_party/flatcc/libflatcc_parsing.a $B/build_tools/third_party/flatcc/libflatcc_runtime.a $B/build_tools/third_party/printf/libprintf_printf.a"
$CC -O2 -std=gnu11 ${EXTRA_CFLAGS:-} -I"$IREE_SRC/runtime/src" -I"$B/runtime/src" \
  -DIREE_ALLOCATOR_SYSTEM_CTL=iree_allocator_libc_ctl -I. \
  native_learner.c -o "$OUT" -Wl,--start-group $LIBS -Wl,--end-group -lm -ldl -lpthread ${EXTRA_LDFLAGS:-}
echo "built $OUT (contract header generated from $CONTRACT; header sha256 $(sha256sum contract_gen.h | cut -c1-16)...)"
ls -l "$OUT" | awk '{print "binary bytes:",$5}'
